### ISSUE TITLE
Doesn't work in Safari

### ISSUE THREAD

**Issue by pinceladasdaweb** [FelixRilling/ok#1]
Because Safari doesn't support html5 validation.

**Comment by FelixRilling** [comment]
I just tested it and you appear to be correct. I'm unsure on how to solve this, as the fix would either require polyfilling the html5 validation or implement a small custom validation. If anyone has an idea, feel free to let me know.

**Comment by pinceladasdaweb** [comment]
My suggestion is to insert a very simple validation.
