### ISSUE TITLE
Need to use multiple validations at once

### ISSUE THREAD

**Issue by x16** [FelixRilling/ok#6]
Great library, a really lightweight interface to attach user validations to form fields. But what if I need to use more than one validation. For example, I have an IP address text field and I need to check it for presence (i.e. check if it is not empty) AND check the IP address format? I know: I can just write my own validator to account both of that conditions but is there any way to do this smarter?

**Comment by FelixRilling** [comment]
Sounds like a good feature, ill work on it when I have the time. Thanks!

**Comment by FelixRilling** [comment]
I could allow the data attribute syntax `data-ok="validator1, valdator2` to chain two or more validators.

**Comment by x16** [comment]
It would be great to chain validation methods.

**Comment by FelixRilling** [comment]
Added in v3.3.0
