### ISSUE TITLE
Why only cutting edge browser support?

### ISSUE THREAD

**Issue by drnkwati** [FelixRilling/ok#7]
This is a very good library but I thing it could be writing to support even ie9
Its solve one problem well but i thing lack of support for ie9 and even ie10 presents a drawback
Can you rework on this?

**Comment by FelixRilling** [comment]
I agree, but this might be hard as the validation API this library uses is not supported in those browsers. I could however only set the invalid CSS class instead of using the Validation API if it is not available.

**Comment by drnkwati** [comment]
ok cool
great work man

**Comment by FelixRilling** [comment]
Added in v3.4.0

**Comment by drnkwati** [comment]
Thanks for the efforts man
But we still have functions like Object.entries(obj) on line 71 which are es2017 
that is not supported even in ie10.

**Comment by FelixRilling** [comment]
oh my, i completely missed that! ill change the babel config to target IE9 and release a fix.

**Comment by FelixRilling** [comment]
Turns out this is more difficult, than I expected, as some of the stuff requires the babel runtime to polyfill. Depending on your use case, running [babel](https://babeljs.io/) over it in your project would be easier, what do you think?

**Comment by drnkwati** [comment]
I have use babel online then stripped off unnecessary code generated.
I wrote comments and links for polyfill were necessary, specifically the Map and Object.entries which are es2016 and 2017 features. I have not noticed any other functions which may require special handling except for the Symbol which I removed from isTypeOf function and simply used typeof val.
NB: I think what you are trying to accomplish with Map and Object.entries can be done with for loops. 
here is my modified version. I hope you can figure out something

`
"use strict";

var _createClass = (function() {
    function defineProperties(target, props) {
        for (var i = 0; i < props.length; i++) {
            var descriptor = props[i];
            descriptor.enumerable = descriptor.enumerable || false;
            descriptor.configurable = true;
            if ("value" in descriptor) descriptor.writable = true;
            Object.defineProperty(target, descriptor.key, descriptor);
        }
    };

    return function(Constructor, protoProps, staticProps) {
        if (protoProps) defineProperties(Constructor.prototype, protoProps);
        if (staticProps) defineProperties(Constructor, staticProps);
        return Constructor;
    };
})();

//
var Ok = (function() {

    "use strict";

    var isTypeOf = function isTypeOf(val, type) {
        return (typeof val === "undefined" ? "undefined" : typeof val) === type;
    };
    var isUndefined = function isUndefined(val) {
        return isTypeOf(val, "undefined");
    };

    // Map ES6
    // (smap.js A forward polyfill for ES6 Maps)
    // Polyfill @ https://github.com/eriwen/smap.js/blob/master/smap.js

    // (Object.entries) ECMAScript 2017 (ECMA-262) Specifications
    // Polyfill @ https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries#Polyfill
    var mapFromObject = function mapFromObject(obj) {
        return new Map(Object.entries(obj));
    };
    var isInputElementCheckboxLike = function isInputElementCheckboxLike(element) {
        return element.type === "checkbox" || element.type === "radio";
    };
    var getInputElementValue = function getInputElementValue(element) {
        return isInputElementCheckboxLike(element) ? element.checked : element.value;
    };
    var hasBrowserValidationSupport = !isUndefined(HTMLInputElement.prototype.setCustomValidity);

    /**
     * @class
     */

    var Ok = (function() {

        /**
         * Ok class.
         *
         * @public
         * @param {object} validators object containing the validators to use.
         * @param {string|false} [invalidClass="invalid"] CSS class for invalid elements, or false if none should be set.
         */
        function Ok(validators) {
            var invalidClass =
                arguments.length > 1 && arguments[1] !== undefined ?
                arguments[1] :
                "invalid";

            this.map = mapFromObject(validators);
            this.invalidClass = invalidClass;
        };

        /**
         * Validates an input element and returns the validity.
         *
         * @public
         * @param {HTMLInputElement} element HTMLInputElement to validate.
         * @param {...any[]} args optional arguments to pass.
         * @returns {boolean} current validity of the element.
         */

        _createClass(Ok, [{
                key: "validate",
                value: function validate(element) {
                    var _this = this;

                    for (
                        var _len = arguments.length,
                            args = Array(_len > 1 ? _len - 1 : 0),
                            _key = 1; _key < _len; _key++
                    ) {
                        args[_key - 1] = arguments[_key];
                    }

                    if (!element.dataset.ok) throw new Error("no validator assigned");
                    var value = getInputElementValue(element);
                    var validatorList = element.dataset.ok.split(",").map(function(str) {
                        return str.trim();
                    });
                    var result = true;
                    validatorList.forEach(function(validatorListEntry) {
                        if (result) {
                            if (!_this.map.has(validatorListEntry))
                                throw new Error(
                                    "missing validator '" + validatorListEntry + "'"
                                );
                            var validator = _this.map.get(validatorListEntry);

                            if (!validator.fn.apply(validator, [value, element].concat(args))) {
                                result = false;
                                if (hasBrowserValidationSupport)
                                    element.setCustomValidity(validator.msg);
                            }
                        }
                    });

                    if (result) {
                        if (hasBrowserValidationSupport) element.setCustomValidity("");
                        if (this.invalidClass) element.classList.remove(this.invalidClass);
                    } else if (this.invalidClass) {
                        element.classList.add(this.invalidClass);
                    }

                    return result;
                }
                /**
                 * Binds an event handler to an input element.
                 *
                 * @public
                 * @param {HTMLInputElement} element HTMLInputElement to bind.
                 * @param {string} [eventType="input"] event type to bind.
                 */
            },
            {
                key: "bind",
                value: function bind(element) {
                    var _this2 = this;

                    var eventType =
                        arguments.length > 1 && arguments[1] !== undefined ?
                        arguments[1] :
                        "input";

                    element.addEventListener(eventType, function(e) {
                        return _this2.validate(element, e);
                    });
                }
            }
        ]);

        return Ok;

    })();

    return Ok;
})();
`

**Comment by FelixRilling** [comment]
Thanks, but this would require me to rewrite the source just to support legacy browsers which I don't really like. depending on where and how you use ok.js, it might be easier to just integrate babel in your build process and transpile it there.
