### ISSUE TITLE
Can We Implement it With React?

### ISSUE THREAD

**Issue by anuraghazra** [FelixRilling/ok#8]

**Comment by anuraghazra** [comment]
I also don't have enough experience on building React Libraries, but i will try to make it work on my own time, and if i succeed  i will make a PR :+1:

**Comment by RillingDev** [comment]
Some time has passed, and I have gotten to work with React.
I am experimenting with an API to make Ok.js easier to use with React and other frameworks, dubbing it the "composition API" - see <https://github.com/FelixRilling/ok/blob/attempts/more-functional/README.md#composition-api> for an example.
